---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-hostpath
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-media
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: smb-test
  resources:
    requests:
      storage: 1Mi