---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zitadel
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zitadel-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Postgres
        ZITADEL_DATABASE_POSTGRES_USER_USERNAME: "{{ .ZITADEL_POSTGRES_USER }}"
        ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: "{{ .ZITADEL_POSTGRES_PASSWORD }}"
        # Postgres Init
        ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: "{{ .POSTGRES_SUPER_USER }}"
        ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: "{{ .POSTGRES_SUPER_PASS }}"
        # Masterkey
        masterkey: "{{ .ZITADEL_MASTERKEY }}"
  dataFrom:
    - extract:
        key: zitadel
    - extract:
        key: cloudnative-pg