apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:d/8dKEJJTsyaZXlDEEjL5CF/z8apkNkG,iv:EixjgJx+rBYT/A8y6yIQD9Ofo19Rnb9vR0ErXvIq7jg=,tag:rTvnF0dnBkSX0GfP8IAmnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1644dw20ks7qmgpggcem7v53hcvc2v7x5kp6e2aqkj262e2zzn99qxmzzrx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4R2xwZVA3SnN2SVYrYkZk
            L1RJbFNjNm9HdHNyVUNBMHk3NFVSSjR2Y0VrCmVIT3hGS2hSVjJ6VTNLVzVkUUxM
            Vi9VbjcrMWlwR3hzZFNTdU5ZZ0N6UTgKLS0tIDFrTm1lQWFZRldYaW5ZM21OclZS
            RHJobXhmekI0NEdydGtZTlRWbzBXc28KSVfYkLeOwsRnJcfkQRKuxH+Ag7lxs0Xe
            tTNI9JUXj42ey4uOgzVb1cFHPKDkTOIqR8r1W1lLLFxjBpBvh+z5Lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-03T23:46:08Z"
    mac: ENC[AES256_GCM,data:AUpMxrvsBe0gI/KUFBzgadCz1BtQEW2aHGuWsZgIHdkjwIJ6Y9zaw9XEQPiMH2wOi0qznlYlLTMsAcBjtKpcSuk9W+SEcAfwCvWgU4KBnrIJZofA/+G4+5Kev5/vIZMTZcClLM5t5PW4G0uqoCwORwYYAVNjGooswRHgQQ2zeMM=,iv:Pt3CcgWdTSkS5SF6IKWfB/DPInkZi8Qhih+JYOLahD0=,tag:tzweQ6/IKAWGcJ1xR0Leng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
