apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:sLeBnpeRTuj4l0Zw2xlir0mTfs9QAj6s,iv:NXUNP93pQKHzBAYFArkNCFfYOnCSyRF7RRxc7cwKglQ=,tag:Vv2vYEXVOhd4jZDcq9u8+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1644dw20ks7qmgpggcem7v53hcvc2v7x5kp6e2aqkj262e2zzn99qxmzzrx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyelByN3N5NDRRNU1TSnNK
            YnFSVm5PV1VPalllTkg5NWhReEFvcWdqYkU4CkJNRnVtR3dGeHdjM2QzMmJmd3p2
            Nlp3aXJ3NGFnbjcvRUxVN2gyajMyOWcKLS0tIEhhV08vLzZoUlpCaXB3MnVTaGJO
            NHhiTTZaREVWdEdzWUdGVzRoclA5S3cK7W1xzFLUiVZZnmhE71aXVrnwCsT4XYE8
            x+LaOeE6pQe02H8Osl9TGU5aPOk4cmOxTS/deq9NisGyNGGUaACAJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T22:23:10Z"
    mac: ENC[AES256_GCM,data:dNLaA6L/TJ1+nklfY15NTjTbAWqCXWnaQTRk2lUYF7pPuS4NPy7btSTz8uNYntfHQay1m3xGw2iJZ8tMyjX3wxAc9rp/zJO0CmshB+RG08Ut9WGnD/tVWb9rcYTfkPOQXTkiZZ70tOBgCWTMhPrEncLnHiNU2zzs6f2UbNJ40Mk=,iv:KysoUxBTHKv2bTZYnCy/B8RhnbaIt+eBtwO/Jlen77I=,tag:sUYIUZ2gReOehfWP1IhyEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
