---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./hajimari/ks.yaml
  - ./homepage/ks.yaml
  - ./prowlarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  - ./radarr/ks.yaml
  - ./overseerr/ks.yaml
  - ./tautulli/ks.yaml