---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: palworld-tools
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: palworld-tools-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        rcon.yaml: |-
          ---
          palworld:
            address: "palworld.games.svc.cluster.local:25575"
            password: "{{ .ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: palworld
