---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: yourspotify-server
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: your-spotify-secret
    template:
      engineVersion: v2
      data:
        YOURSPOTIFY_CLIENT-ID: "{{ .YOURSPOTIFY_CLIENT-ID }}"
        YOURSPOTIFY_SECRET: "{{ .YOURSPOTIFY_SECRET }}"
        YOURSPOTIFY_MONGODB-URL: "{{ .YOURSPOTIFY_MONGODB-URL }}"
  dataFrom:
    - extract:
        key: your-spotify