---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-hostpath
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "sonarr-config-dst"
  resources:
    requests:
      storage: 8Gi