---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-hostpath
  resources:
    requests:
      storage: 8Gi