---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: sonarr
  namespace: default
spec:
  sourcePVC: sonarr-config
  trigger:
    schedule: "0 * * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: sonarr-secret
    cacheCapacity: 8Gi
    cacheStorageClassName: local-path
    cacheAccessModes: [ReadWriteOnce]
    accessModes: [ReadWriteOnce]
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      hourly: 24
      daily: 7
      weekly: 5
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "sonarr-config-dst"
  namespace: default
spec:
  trigger:
    manual: restore-once
  restic:
    repository: sonarr-secret
    copyMethod: Snapshot # must be Snapshot
    cacheCapacity: 8Gi
    cacheStorageClassName: local-path
    cacheAccessModes: [ReadWriteOnce]
    accessModes: [ReadWriteOnce]
    capacity: 8Gi