---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: monica
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: monica-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_CONNECTION: pgsql
        DB_DATABASE: &dbName monica
        DB_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        MAIL_USERNAME: "{{ .SENDGRID_USERNAME }}"
        MAIL_PASSWORD: "{{ .SENDGRID_PASSWORD }}"
        MAIL_HOST: "{{ .SENDGRID_HOST }}"
        MAIL_FROM_ADDRESS: monica{{ .SENDGRID_BASEADDRESS }}
        DB_USERNAME: &dbUser "{{ .MONICA_DB_USERNAME }}"
        DB_PASSWORD: &dbPass "{{ .MONICA_DB_PASSWORD }}"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: monica
    - extract:
        key: SendGrid