---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: firefly
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: firefly-secret
    template:
      engineVersion: v2
      data:
        APP_KEY: "{{ .FIREFLY_APP_KEY }}"
        NORDIGEN_ID: "{{ .FIREFLY_NORDIGEN_ID }}"
        NORDIGEN_KEY: "{{ .FIREFLY_NORDIGEN_KEY }}"
        DB_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        DB_DATABASE: &dbName firefly
        DB_USERNAME: &dbUser "{{ .FIREFLY_POSTGRES_USER }}"
        DB_PASSWORD: &dbPass "{{ .FIREFLY_POSTGRES_PASS }}"

        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

  dataFrom:
    - extract:
        key: firefly
    - extract:
        key: cloudnative-pg