---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app firefly
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        pod:
          automountServiceAccountToken: false
          enableServiceLinks: false
          annotations:
            reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
             repository: ghcr.io/onedr0p/postgres-init
             tag: 16.0
            imagePullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: firefly-secret

        containers:
          main:
            image:
              repository: fireflyiii/core
              tag: version-6.1.13
            env:
              TZ: Europe/London
              APP_URL: "https://{{ .Release.Name }}.${SECRET_DOMAIN}"
              APP_ENV: "production"
              DB_CONNECTION: "pgsql"
              DB_HOST: postgres16-rw.database.svc.cluster.local
              DB_PORT: "5432"
              MAIL_MAILER: log
              TRUSTED_PROXIES: "**" # TODO: This should be changed..
              SEND_REGISTRATION_MAIL: false
              SEND_ERROR_MESSAGE: false
              SEND_LOGIN_NEW_IP_WARNING: false
              COOKIE_DOMAIN: "{{ .Release.Name }}.${SECRET_DOMAIN}"
              COOKIE_SECURE: "true"
              COOKIE_SAMESITE: "lax"
              # Requires version 6.0.21.
              #FIREFLY_III_LAYOUT: v2
            envFrom:
              - secretRef:
                  name: firefly-secret
            resources:
              requests:
                cpu: 100m
                memory: 256Mi

    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        className: "internal"
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Finance Manager
          gethomepage.dev/group: Apps
          gethomepage.dev/icon: firefly.png
          gethomepage.dev/name: Firefly-iii
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      upload:
        enabled: true
        existingClaim: *app
        advancedMounts:
          main:
            main:
              - path: /var/www/html/storage/upload
      logs:
        enabled: true
        type: emptyDir
        advancedMounts:
          main:
            main:
              - path: /var/www/html/storage/logs