apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:beltj0xxAm12zelUOwJwFo4qOp5c50+PfAE3HCdT2YXrUbTSe9uBmQ==,iv:Csn0YNqPhJklmBsdrhdYq78mY6HPFo3PJqFglodXeMQ=,tag:1HsM3eu/OAxWZfbUJaVZLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1644dw20ks7qmgpggcem7v53hcvc2v7x5kp6e2aqkj262e2zzn99qxmzzrx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdFcvYXpsV0ZnNDVUMXFk
            ZmtQVFQvRVpyaFdaODJqazk5aEFuVXRnVGxzCmY3bGloV3FtczFVcXZULzl0anlX
            MldxRXFXRnFDQ3YrckMzd0hHWTFmNVUKLS0tIEhySEY3SDZySEM1bERLNjRMVXQ2
            QmFTRURCZ0lLN0JwRVNNVThsOE5rYmMKTF2GL+BlMo/bIJ2+N/+9dzxNgDalu9dH
            g0h8FS0+NyYGIpVsKvvup7a/sCcr8XLOl7Tj2EkoWkBPxFiKoXawoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T22:23:10Z"
    mac: ENC[AES256_GCM,data:uuEkX3uhSSr5wBkweBPUDs7S1igJfXdUAstEtiSWGLCFpxMs3A/674d4yUgU0LR12W//QlVRmjye4qOYvhGI4Z3Fd2JMGz87GxzJCwO7cUqrcwHqTuplJRQcCyVKMFYzRKKg71BOWvlAKaTkHSAAQPft/ZOPbkkMDhuCeCCzqrQ=,iv:2dHhQlL4wm6PXSeXzRRcSupl4CI/T7lwxpJROk5pWwg=,tag:AsJ0Phnrp/NLWI892rFZog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
