---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: firefly-importer
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: firefly-importer-secret
    template:
      engineVersion: v2
      data:
        NORDIGEN_ID: "{{ .FIREFLY_NORDIGEN_ID }}"
        NORDIGEN_KEY: "{{ .FIREFLY_NORDIGEN_KEY }}"
        IMPORTER: "{{ .IMPORTER_ACCESS_TOKEN }}"
  dataFrom:
    - extract:
        key: firefly