---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefly-importer
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        pod:
          automountServiceAccountToken: false
          enableServiceLinks: false
          annotations:
            reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: fireflyiii/data-importer
              tag: version-1.4.4
            env:
              TRUSTED_PROXIES: "**"
              FIREFLY_III_URL: "http://firefly.default.svc.cluster.local:8080"
              VANITY_URL: "https://firefly.${SECRET_DOMAIN}"
              FIREFLY_III_ACCESS_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: firefly-importer-secret
                    key: IMPORTER
            envFrom:
              - secretRef:
                  name: firefly-importer-secret
            resources:
              requests:
                memory: 256Mi

    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        className: "internal"
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Data Importer for Firefly
          gethomepage.dev/group: Apps
          gethomepage.dev/icon: firefly.png
          gethomepage.dev/name: Firefly-iii Data Importer
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host